### ISSUE TITLE
Pela logic fixes

### ISSUE THREAD

**Issue by unleashurgeek** [simimpact/srsim#45]
Following logic in Pela implementation should be changed to match game:
- [x] E1: Pela gains energy when any ally kills an enemy (should change to `TargetDeath` event subscription)
- [x] E6: Only living targets get hit (game uses `Retarget` for E6: https://github.com/simimpact/srsim/issues/44)
- [x] Talent: Only living targets that were hit count towards the Debuff Counter (game uses `Retarget`: https://github.com/simimpact/srsim/issues/44)
- [x] (from https://github.com/simimpact/srsim/issues/19): A4 `OnBeforeDying` case
